CREATE TABLE distributeurs(
   region          VARCHAR(26) 
  ,id_departement  VARCHAR(3)
  ,departement     VARCHAR(23)
  ,nb_distributeur INTEGER
);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('ALSACE','67','BAS-RHIN',73);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('ALSACE','68','HAUT-RHIN',60);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('AQUITAINE','24','DORDOGNE',28);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('AQUITAINE','33','GIRONDE',76);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('AQUITAINE','40','LANDES',22);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('AQUITAINE','47','LOT-ET-GARONNE',36);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('AQUITAINE','64','PYRENEES-ATLANTIQUES',27);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('AUVERGNE','3','ALLIER',23);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('AUVERGNE','15','CANTAL',11);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('AUVERGNE','43','HAUTE-LOIRE',13);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('AUVERGNE','63','PUY-DE-DOME',24);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('BASSE-NORMANDIE','14','CALVADOS',33);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('BASSE-NORMANDIE','50','MANCHE',30);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('BASSE-NORMANDIE','61','ORNE',8);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('BOURGOGNE','21','COTE-D''OR',41);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('BOURGOGNE','58','NIEVRE',7);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('BOURGOGNE','71','SAONE-ET-LOIRE',27);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('BOURGOGNE','89','YONNE',14);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('BRETAGNE','22','COTES-D''ARMOR',45);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('BRETAGNE','29','FINISTERE',89);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('BRETAGNE','35','ILLE-ET-VILAINE',74);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('BRETAGNE','56','MORBIHAN',46);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('CENTRE','18','CHER',8);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('CENTRE','28','EURE-ET-LOIR',11);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('CENTRE','36','INDRE',6);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('CENTRE','37','INDRE-ET-LOIRE',23);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('CENTRE','41','LOIR-ET-CHER',9);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('CENTRE','45','LOIRET',23);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('CHAMPAGNE-ARDENNE','8','ARDENNES',9);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('CHAMPAGNE-ARDENNE','10','AUBE',13);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('CHAMPAGNE-ARDENNE','51','MARNE',23);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('CHAMPAGNE-ARDENNE','52','HAUTE-MARNE',4);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('CORSE','2A','CORSE-DU-SUD',6);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('CORSE','2B','HAUTE-CORSE',5);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('FRANCHE-COMTE','25','DOUBS',15);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('FRANCHE-COMTE','39','JURA',20);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('FRANCHE-COMTE','70','HAUTE-SAONE',15);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('FRANCHE-COMTE','90','TERRITOIRE DE BELFORT',6);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('HAUTE-NORMANDIE','27','EURE',9);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('HAUTE-NORMANDIE','76','SEINE-MARITIME',36);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('ILE-DE-FRANCE','75','PARIS',119);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('ILE-DE-FRANCE','77','SEINE-ET-MARNE',41);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('ILE-DE-FRANCE','78','YVELINES',54);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('ILE-DE-FRANCE','91','ESSONNE',55);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('ILE-DE-FRANCE','92','HAUTS-DE-SEINE',56);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('ILE-DE-FRANCE','93','SEINE-SAINT-DENIS',18);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('ILE-DE-FRANCE','94','VAL-DE-MARNE',97);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('ILE-DE-FRANCE','95','VAL-D''OISE',23);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('LANGUEDOC-ROUSSILLON','11','AUDE',20);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('LANGUEDOC-ROUSSILLON','30','GARD',54);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('LANGUEDOC-ROUSSILLON','34','HERAULT',82);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('LANGUEDOC-ROUSSILLON','48','LOZERE',3);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('LANGUEDOC-ROUSSILLON','66','PYRENEES-ORIENTALES',48);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('LIMOUSIN','19','CORREZE',12);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('LIMOUSIN','23','CREUSE',5);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('LIMOUSIN','87','HAUTE-VIENNE',15);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('LORRAINE','54','MEURTHE-ET-MOSELLE',18);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('LORRAINE','55','MEUSE',7);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('LORRAINE','57','MOSELLE',32);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('LORRAINE','88','VOSGES',16);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('MIDI-PYRENEES','9','ARIEGE',12);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('MIDI-PYRENEES','12','AVEYRON',32);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('MIDI-PYRENEES','31','HAUTE-GARONNE',54);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('MIDI-PYRENEES','32','GERS',20);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('MIDI-PYRENEES','46','LOT',15);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('MIDI-PYRENEES','65','HAUTES-PYRENEES',9);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('MIDI-PYRENEES','81','TARN',22);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('MIDI-PYRENEES','82','TARN-ET-GARONNE',26);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('NORD-PAS-DE-CALAIS','59','NORD',77);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('NORD-PAS-DE-CALAIS','62','PAS-DE-CALAIS',46);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('OUTRE-MER','971','GUADELOUPE',NULL);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('OUTRE-MER','972','MARTINIQUE',NULL);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('OUTRE-MER','973','GUYANE',NULL);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('OUTRE-MER','974','LA REUNION',4);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('PAYS DE LA LOIRE','44','LOIRE-ATLANTIQUE',76);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('PAYS DE LA LOIRE','49','MAINE-ET-LOIRE',45);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('PAYS DE LA LOIRE','53','MAYENNE',28);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('PAYS DE LA LOIRE','72','SARTHE',15);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('PAYS DE LA LOIRE','85','VENDEE',32);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('PICARDIE','2','AISNE',12);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('PICARDIE','60','OISE',29);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('PICARDIE','80','SOMME',12);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('POITOU-CHARENTES','16','CHARENTE',23);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('POITOU-CHARENTES','17','CHARENTE-MARITIME',24);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('POITOU-CHARENTES','79','DEUX-SEVRES',21);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('POITOU-CHARENTES','86','VIENNE',9);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('PROVENCE-ALPES-COTE D AZUR','4','ALPES-DE-HAUTE-PROVENCE',20);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('PROVENCE-ALPES-COTE D AZUR','5','HAUTES-ALPES',18);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('PROVENCE-ALPES-COTE D AZUR','6','ALPES-MARITIMES',52);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('PROVENCE-ALPES-COTE D AZUR','13','BOUCHES-DU-RHONE',118);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('PROVENCE-ALPES-COTE D AZUR','83','VAR',58);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('PROVENCE-ALPES-COTE D AZUR','84','VAUCLUSE',86);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('RHONE-ALPES','1','AIN',19);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('RHONE-ALPES','7','ARDECHE',24);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('RHONE-ALPES','26','DROME',55);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('RHONE-ALPES','38','ISERE',53);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('RHONE-ALPES','42','LOIRE',34);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('RHONE-ALPES','69','RHONE',91);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('RHONE-ALPES','73','SAVOIE',28);
INSERT INTO distributeurs(region,id_departement,departement,nb_distributeur) VALUES ('RHONE-ALPES','74','HAUTE-SAVOIE',46);
