CREATE TABLE population_dpt(
   region          VARCHAR(26)
  ,id_departement  VARCHAR(3)
  ,nom_departement VARCHAR(23)
  ,nb_communes     INTEGER
  ,population      INTEGER
);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('RHONE-ALPES','01','AIN',419,636916);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('PICARDIE','02','AISNE',816,554512);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('AUVERGNE','03','ALLIER',320,353742);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('PROVENCE-ALPES-COTE D''AZUR','04','ALPES-DE-HAUTE-PROVENCE',200,166726);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('PROVENCE-ALPES-COTE D''AZUR','05','HAUTES-ALPES',172,144640);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('PROVENCE-ALPES-COTE D''AZUR','06','ALPES-MARITIMES',163,1096741);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('RHONE-ALPES','07','ARDECHE',339,330017);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('CHAMPAGNE-ARDENNE','08','ARDENNES',463,289075);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('MIDI-PYRENEES','09','ARIEGE',332,158379);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('CHAMPAGNE-ARDENNE','10','AUBE',433,314825);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('LANGUEDOC-ROUSSILLON','11','AUDE',438,374868);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('MIDI-PYRENEES','12','AVEYRON',304,289257);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('PROVENCE-ALPES-COTE D''AZUR','13','BOUCHES-DU-RHONE',119,2022604);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('BASSE-NORMANDIE','14','CALVADOS',705,706635);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('AUVERGNE','15','CANTAL',260,152797);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('POITOU-CHARENTES','16','CHARENTE',404,366587);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('POITOU-CHARENTES','17','CHARENTE-MARITIME',472,652610);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('CENTRE','18','CHER',290,319693);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('LIMOUSIN','19','CORREZE',286,249452);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('CORSE','2A','CORSE-DU-SUD',124,151621);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('CORSE','2B','HAUTE-CORSE',236,173889);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('BOURGOGNE','21','COTE-D''OR',706,543648);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('BRETAGNE','22','COTES-D''ARMOR',373,617565);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('LIMOUSIN','23','CREUSE',260,125714);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('AQUITAINE','24','DORDOGNE',557,429579);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('FRANCHE-COMTE','25','DOUBS',593,548026);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('RHONE-ALPES','26','DROME',369,509444);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('HAUTE-NORMANDIE','27','EURE',675,612518);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('CENTRE','28','EURE-ET-LOIR',401,444385);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('BRETAGNE','29','FINISTERE',283,934625);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('LANGUEDOC-ROUSSILLON','30','GARD',353,750025);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('MIDI-PYRENEES','31','HAUTE-GARONNE',589,1325392);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('MIDI-PYRENEES','32','GERS',463,197598);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('AQUITAINE','33','GIRONDE',542,1536448);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('LANGUEDOC-ROUSSILLON','34','HERAULT',343,1111881);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('BRETAGNE','35','ILLE-ET-VILAINE',353,1047873);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('CENTRE','36','INDRE',247,235181);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('CENTRE','37','INDRE-ET-LOIRE',277,615557);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('RHONE-ALPES','38','ISERE',532,1263850);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('FRANCHE-COMTE','39','JURA',544,270914);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('AQUITAINE','40','LANDES',331,411197);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('CENTRE','41','LOIR-ET-CHER',291,342471);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('RHONE-ALPES','42','LOIRE',327,774144);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('AUVERGNE','43','HAUTE-LOIRE',260,233918);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('PAYS DE LA LOIRE','44','LOIRE-ATLANTIQUE',221,1364453);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('CENTRE','45','LOIRET',334,684104);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('MIDI-PYRENEES','46','LOT',340,180470);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('AQUITAINE','47','LOT-ET-GARONNE',319,343645);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('LANGUEDOC-ROUSSILLON','48','LOZERE',185,80712);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('PAYS DE LA LOIRE','49','MAINE-ET-LOIRE',357,823546);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('BASSE-NORMANDIE','50','MANCHE',601,518364);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('CHAMPAGNE-ARDENNE','51','MARNE',620,583691);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('CHAMPAGNE-ARDENNE','52','HAUTE-MARNE',437,188083);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('PAYS DE LA LOIRE','53','MAYENNE',261,318095);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('LORRAINE','54','MEURTHE-ET-MOSELLE',594,745398);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('LORRAINE','55','MEUSE',501,198334);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('BRETAGNE','56','MORBIHAN',261,761433);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('LORRAINE','57','MOSELLE',730,1068119);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('BOURGOGNE','58','NIEVRE',312,222688);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('NORD-PAS-DE-CALAIS','59','NORD',650,2635494);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('PICARDIE','60','OISE',692,835918);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('BASSE-NORMANDIE','61','ORNE',495,298248);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('NORD-PAS-DE-CALAIS','62','PAS-DE-CALAIS',895,1491735);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('AUVERGNE','63','PUY-DE-DOME',470,658489);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('AQUITAINE','64','PYRENEES-ATLANTIQUES',547,685564);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('MIDI-PYRENEES','65','HAUTES-PYRENEES',474,236728);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('LANGUEDOC-ROUSSILLON','66','PYRENEES-ORIENTALES',226,471573);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('ALSACE','67','BAS-RHIN',527,1128825);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('ALSACE','68','HAUT-RHIN',377,774976);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('RHONE-ALPES','69','RHONE',287,1812196);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('FRANCHE-COMTE','70','HAUTE-SAONE',545,246782);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('BOURGOGNE','71','SAONE-ET-LOIRE',572,575097);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('PAYS DE LA LOIRE','72','SARTHE',370,584865);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('RHONE-ALPES','73','SAVOIE',304,437915);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('RHONE-ALPES','74','HAUTE-SAVOIE',294,793342);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('ILE-DE-FRANCE','75','PARIS',1,2254262);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('HAUTE-NORMANDIE','76','SEINE-MARITIME',745,1280410);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('ILE-DE-FRANCE','77','SEINE-ET-MARNE',513,1387830);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('ILE-DE-FRANCE','78','YVELINES',262,1446301);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('POITOU-CHARENTES','79','DEUX-SEVRES',303,383079);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('PICARDIE','80','SOMME',782,584184);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('MIDI-PYRENEES','81','TARN',323,393877);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('MIDI-PYRENEES','82','TARN-ET-GARONNE',195,256867);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('PROVENCE-ALPES-COTE D''AZUR','83','VAR',153,1046346);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('PROVENCE-ALPES-COTE D''AZUR','84','VAUCLUSE',151,562254);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('PAYS DE LA LOIRE','85','VENDEE',282,674843);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('POITOU-CHARENTES','86','VIENNE',281,442696);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('LIMOUSIN','87','HAUTE-VIENNE',201,384411);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('LORRAINE','88','VOSGES',514,388551);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('BOURGOGNE','89','YONNE',455,352182);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('FRANCHE-COMTE','90','TERRITOIRE DE BELFORT',102,147777);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('ILE-DE-FRANCE','91','ESSONNE',196,1273233);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('ILE-DE-FRANCE','92','HAUTS-DE-SEINE',36,1611290);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('ILE-DE-FRANCE','93','SEINE-SAINT-DENIS',40,1565222);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('ILE-DE-FRANCE','94','VAL-DE-MARNE',47,1367091);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('ILE-DE-FRANCE','95','VAL-D''OISE',185,1211138);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('GUADELOUPE','971','GUADELOUPE',32,409055);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('MARTINIQUE','972','MARTINIQUE',34,391837);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('GUYANE','973','GUYANE',22,246507);
INSERT INTO population_dpt(region,id_departement,nom_departement,nb_communes,population) VALUES ('LA REUNION','974','LA REUNION',24,844741);
