CREATE TABLE isf_france(
   region           VARCHAR(26) NOT NULL 
  ,departement      VARCHAR(26) NOT NULL
  ,commune          VARCHAR(26) NOT NULL
  ,nb_redevables    INTEGER  NOT NULL
  ,patrimoine_moyen INTEGER  NOT NULL
  ,impot_moyen      NUMERIC(8,2) NOT NULL
);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ALSACE','BAS-RHIN','HAGUENAU',225,1601216,5288.87);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ALSACE','BAS-RHIN','ILLKIRCH-GRAFFENSTADEN',192,1318253,2243.36);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ALSACE','BAS-RHIN','SCHILTIGHEIM',129,1543677,3923.59);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ALSACE','BAS-RHIN','STRASBOURG',2625,1838304,6596.31);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ALSACE','HAUT-RHIN','COLMAR',436,1581189,4490.99);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ALSACE','HAUT-RHIN','MULHOUSE',551,1680184,5000.26);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ALSACE','HAUT-RHIN','SAINT-LOUIS',98,1599268,4705.28);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AQUITAINE','DORDOGNE','BERGERAC',199,1430179,3495.08);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AQUITAINE','DORDOGNE','PERIGUEUX',210,1605537,6142.17);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AQUITAINE','GIRONDE','BEGLES',77,1384439,3138.97);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AQUITAINE','GIRONDE','BORDEAUX',3434,1667444,5416.83);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AQUITAINE','GIRONDE','GRADIGNAN',233,1437001,4273.27);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AQUITAINE','GIRONDE','LA TESTE-DE-BUCH',384,1486431,3986.49);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AQUITAINE','GIRONDE','LE BOUSCAT',486,2044199,8755.28);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AQUITAINE','GIRONDE','LIBOURNE',218,1634528,5116.85);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AQUITAINE','GIRONDE','MERIGNAC',486,1401971,3145.51);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AQUITAINE','GIRONDE','PESSAC',422,1440228,4142);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AQUITAINE','GIRONDE','SAINT-MEDARD-EN-JALLES',189,1384940,3122.24);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AQUITAINE','GIRONDE','TALENCE',295,1374940,2911.41);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AQUITAINE','GIRONDE','VILLENAVE-D''ORNON',137,1896527,7564.48);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AQUITAINE','LANDES','DAX',207,1627975,5492.82);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AQUITAINE','LANDES','MONT-DE-MARSAN',160,1428270,3425.53);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AQUITAINE','LOT-ET-GARONNE','AGEN',202,1571790,4941.78);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AQUITAINE','LOT-ET-GARONNE','VILLENEUVE-SUR-LOT',158,1410958,3279.65);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AQUITAINE','PYRENEES-ATLANTIQUES','ANGLET',666,1464414,4010.93);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AQUITAINE','PYRENEES-ATLANTIQUES','BAYONNE',397,1566606,4746.23);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AQUITAINE','PYRENEES-ATLANTIQUES','BIARRITZ',815,1534830,4610.61);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AQUITAINE','PYRENEES-ATLANTIQUES','PAU',813,1427079,3798.38);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AUVERGNE','ALLIER','MONTLUCON',232,1580665,4535.56);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AUVERGNE','ALLIER','MOULINS',125,1476010,3437.99);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AUVERGNE','ALLIER','VICHY',325,1423028,3993.49);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AUVERGNE','CANTAL','AURILLAC',211,1490386,4314.37);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AUVERGNE','HAUTE-LOIRE','LE PUY-EN-VELAY',115,1553252,4295.59);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('AUVERGNE','PUY-DE-DOME','CLERMONT-FERRAND',842,1535436,4934.06);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BASSE-NORMANDIE','CALVADOS','CAEN',1055,1616683,5112.24);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BASSE-NORMANDIE','CALVADOS','LISIEUX',119,1471471,4062.3);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BASSE-NORMANDIE','MANCHE','CHERBOURG-OCTEVILLE',221,1462335,3276.01);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BASSE-NORMANDIE','MANCHE','SAINT-LO',107,1434772,3667.95);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BASSE-NORMANDIE','ORNE','ALENCON',149,1531472,4027.06);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BOURGOGNE','COTE-D''OR','BEAUNE',237,1569816,3923.11);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BOURGOGNE','COTE-D''OR','DIJON',1290,1577565,5062.54);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BOURGOGNE','NIEVRE','NEVERS',218,1560105,5445.5);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BOURGOGNE','SAONE-ET-LOIRE','CHALON-SUR-SAONE',277,1458286,3898.47);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BOURGOGNE','SAONE-ET-LOIRE','LE CREUSOT',82,1337818,3128.38);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BOURGOGNE','SAONE-ET-LOIRE','MACON',208,1658105,7137.92);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BOURGOGNE','SAONE-ET-LOIRE','MONTCEAU-LES-MINES',53,1358460,3608);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BOURGOGNE','YONNE','AUXERRE',262,1425504,3327.29);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BOURGOGNE','YONNE','SENS',190,1668679,6139.69);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BRETAGNE','COTES-D''ARMOR','LANNION',164,1293238,2784.02);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BRETAGNE','COTES-D''ARMOR','SAINT-BRIEUC',358,1500405,3734.57);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BRETAGNE','FINISTERE','BREST',524,1729003,5311.06);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BRETAGNE','FINISTERE','CONCARNEAU',188,1646354,5057.41);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BRETAGNE','FINISTERE','QUIMPER',447,1564782,4236.81);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BRETAGNE','ILLE-ET-VILAINE','FOUGERES',132,1464210,3781.04);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BRETAGNE','ILLE-ET-VILAINE','RENNES',2152,1690550,5624.03);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BRETAGNE','ILLE-ET-VILAINE','SAINT-MALO',740,1478798,3887.93);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BRETAGNE','MORBIHAN','LORIENT',291,1456145,3383.81);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('BRETAGNE','MORBIHAN','VANNES',843,1496825,3875.47);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('CENTRE','CHER','BOURGES',434,1665100,5748.44);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('CENTRE','CHER','VIERZON',115,1429152,4272.02);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('CENTRE','EURE-ET-LOIR','CHARTRES',476,1525929,4457.99);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('CENTRE','EURE-ET-LOIR','DREUX',128,1643486,5381.69);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('CENTRE','INDRE','CHATEAUROUX',242,1794322,7432.15);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('CENTRE','INDRE-ET-LOIRE','JOUE-LES-TOURS',162,1484591,3653.96);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('CENTRE','INDRE-ET-LOIRE','TOURS',1201,1516153,4300.34);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('CENTRE','LOIR-ET-CHER','BLOIS',305,1457265,4096.57);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('CENTRE','LOIRET','FLEURY-LES-AUBRAIS',56,1388207,3218.23);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('CENTRE','LOIRET','OLIVET',348,1440571,3553.43);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('CENTRE','LOIRET','ORLEANS',1058,1498831,4170.79);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('CHAMPAGNE-ARDENNE','ARDENNES','CHARLEVILLE-MEZIERES',231,1452575,3921.14);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('CHAMPAGNE-ARDENNE','AUBE','TROYES',375,1640847,5239.7);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('CHAMPAGNE-ARDENNE','HAUTE-MARNE','CHAUMONT',95,1531496,4729.93);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('CHAMPAGNE-ARDENNE','HAUTE-MARNE','SAINT-DIZIER',87,2152899,8364.36);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('CHAMPAGNE-ARDENNE','MARNE','CHALONS-EN-CHAMPAGNE',217,1550958,4047.34);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('CHAMPAGNE-ARDENNE','MARNE','EPERNAY',175,1791918,7122.77);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('CHAMPAGNE-ARDENNE','MARNE','REIMS',1201,1724757,5691.19);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('CORSE','CORSE-DU-SUD','AJACCIO',297,1813666,7130.95);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('CORSE','HAUTE-CORSE','BASTIA',134,1753368,6491.42);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('FRANCHE-COMTE','DOUBS','BESANCON',697,1606235,4839.88);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('FRANCHE-COMTE','DOUBS','MONTBELIARD',127,1379368,3439.57);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('FRANCHE-COMTE','JURA','DOLE',126,1412815,3260.83);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('FRANCHE-COMTE','TERRITOIRE DE BELFORT','BELFORT',204,1570734,4738.49);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('GUADELOUPE','GUADELOUPE','LE GOSIER',98,1885620,7378.52);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('GUYANE','GUYANE','CAYENNE',60,2495190,15043.9);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('HAUTE-NORMANDIE','EURE','EVREUX',290,1506603,3945.46);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('HAUTE-NORMANDIE','EURE','VERNON',180,1514990,4148.37);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('HAUTE-NORMANDIE','SEINE-MARITIME','DIEPPE',190,1444334,3629.74);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('HAUTE-NORMANDIE','SEINE-MARITIME','LE HAVRE',729,1484125,4226.81);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('HAUTE-NORMANDIE','SEINE-MARITIME','MONT-SAINT-AIGNAN',516,1740673,7256.51);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('HAUTE-NORMANDIE','SEINE-MARITIME','ROUEN',889,1563781,4874.42);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('HAUTE-NORMANDIE','SEINE-MARITIME','SOTTEVILLE-LES-ROUEN',60,1324226,2443.1);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','ESSONNE','ATHIS-MONS',140,1425622,4117.44);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','ESSONNE','BRETIGNY-SUR-ORGE',112,1309435,2695.74);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','ESSONNE','BRUNOY',325,1445453,3712.71);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','ESSONNE','CORBEIL-ESSONNES',131,1439541,3712.8);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','ESSONNE','DRAVEIL',238,1546500,4792.96);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','ESSONNE','ETAMPES',118,1597900,4915.9);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','ESSONNE','EVRY',67,1331925,2528.67);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','ESSONNE','GIF-SUR-YVETTE',691,1438342,3661.33);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','ESSONNE','LONGJUMEAU',98,1442013,3251.86);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','ESSONNE','MASSY',198,1260468,2519.71);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','ESSONNE','MONTGERON',294,1416638,3565.35);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','ESSONNE','MORSANG-SUR-ORGE',143,1527515,4916.99);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','ESSONNE','PALAISEAU',404,1766545,6742.79);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','ESSONNE','RIS-ORANGIS',101,1506586,4908.89);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','ESSONNE','SAINT-MICHEL-SUR-ORGE',104,1283549,2939.5);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','ESSONNE','SAINTE-GENEVIEVE-DES-BOIS',246,1466029,4337.26);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','ESSONNE','SAVIGNY-SUR-ORGE',307,1277281,2743.21);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','ESSONNE','VIGNEUX-SUR-SEINE',72,1230559,2435.42);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','ESSONNE','VIRY-CHATILLON',121,1286530,2714.64);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','ESSONNE','YERRES',255,1353543,2830.44);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','ANTONY',1430,1385698,3214.11);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','ASNIERES-SUR-SEINE',1267,1549380,4645.29);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','BAGNEUX',142,1363983,3390.3);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','BOIS-COLOMBES',512,1416954,3555.26);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','BOULOGNE-BILLANCOURT',5083,1871664,7096.56);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','CHATENAY-MALABRY',526,1503305,4679.15);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','CHATILLON',384,1423432,3628.19);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','CLAMART',1141,1463857,3868.35);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','CLICHY',230,1402774,3502.43);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','COLOMBES',722,1497589,3895.6);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','COURBEVOIE',1711,1443843,3659.95);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','FONTENAY-AUX-ROSES',493,1352722,2885.83);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','ISSY-LES-MOULINEAUX',1203,1508122,3905.05);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','LA GARENNE-COLOMBES',519,1420952,3417.76);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','LE PLESSIS-ROBINSON',306,1375072,2991.75);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','LEVALLOIS-PERRET',1694,1688406,4911.02);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','MALAKOFF',228,1670582,7149.4);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','MEUDON',1621,1602743,4517.27);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','MONTROUGE',626,1610527,6377.58);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','NANTERRE',449,1338823,2775.49);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','NEUILLY-SUR-SEINE',7442,3180555,21439.32);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','PUTEAUX',522,1489211,3820.16);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','RUEIL-MALMAISON',2409,1589917,4660.57);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','SAINT-CLOUD',2024,2174346,9877.64);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','SEVRES',937,1655694,4493.07);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','SURESNES',882,1616253,4397.11);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','HAUTS-DE-SEINE','VANVES',525,1493844,3833.39);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','PARIS','PARIS',952,2288274,11168.67);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','PARIS','PARIS',580,1729238,4790.94);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','PARIS','PARIS',1374,1883057,6656.23);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','PARIS','PARIS',1567,2377677,11567.25);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','PARIS','PARIS',3579,1945239,7633.35);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','PARIS','PARIS',4802,2665758,13920.49);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','PARIS','PARIS',7090,3310173,20958.28);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','PARIS','PARIS',4039,2812032,15263.5);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','PARIS','PARIS',2343,1806306,6239.15);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','PARIS','PARIS',1325,1577029,4615.58);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','PARIS','PARIS',2923,1584543,4999.6);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','PARIS','PARIS',3453,1585314,4887);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','PARIS','PARIS',3158,1568969,4760.14);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','PARIS','PARIS',4794,1755652,6151.77);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','PARIS','PARIS',9543,1700128,5629.22);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','PARIS','PARIS',18574,2777748,15552.39);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','PARIS','PARIS',8144,2130124,8876.38);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','PARIS','PARIS',2116,1760570,6516.16);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','PARIS','PARIS',1681,1569489,4648.46);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','PARIS','PARIS',1827,1455881,3917.5);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-ET-MARNE','CHAMPS-SUR-MARNE',81,1302316,2703.65);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-ET-MARNE','CHELLES',262,1349999,3277.2);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-ET-MARNE','COMBS-LA-VILLE',87,1431919,3812.46);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-ET-MARNE','DAMMARIE-LES-LYS',94,1418893,2940.79);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-ET-MARNE','LAGNY-SUR-MARNE',185,1671625,5845.15);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-ET-MARNE','LE MEE-SUR-SEINE',55,1840467,5794.02);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-ET-MARNE','MEAUX',242,1578994,4552.32);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-ET-MARNE','MELUN',207,1607180,5002.25);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-ET-MARNE','OZOIR-LA-FERRIERE',128,1597656,6016.64);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-ET-MARNE','PONTAULT-COMBAULT',169,1335691,3444.56);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-ET-MARNE','VILLEPARISIS',60,1270396,2418.83);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','AUBERVILLIERS',94,1595730,5483.06);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','AULNAY-SOUS-BOIS',332,1415243,3831.54);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','BAGNOLET',80,1397412,3083.71);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','BONDY',88,1424081,3706.18);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','DRANCY',155,1461371,3779.23);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','EPINAY-SUR-SEINE',96,1397695,3228.82);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','GAGNY',241,1339299,3076.79);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','LE BLANC-MESNIL',121,1349020,3273.74);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','LES LILAS',184,1683504,6174.8);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','LES PAVILLONS-SOUS-BOIS',148,1445667,3691.73);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','LIVRY-GARGAN',205,1384756,3676.15);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','MONTFERMEIL',111,1378548,3192.48);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','MONTREUIL',382,1449164,3790.55);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','NEUILLY-PLAISANCE',153,1329263,2750.29);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','NEUILLY-SUR-MARNE',52,1533084,4581.83);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','NOISY-LE-GRAND',309,1416949,3686.22);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','NOISY-LE-SEC',133,1422319,3706.49);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','PANTIN',162,1384082,3410.46);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','ROMAINVILLE',67,1361469,2725.25);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','ROSNY-SOUS-BOIS',212,1370182,3374.12);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','SAINT-DENIS',101,1455987,3819.1);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','SAINT-OUEN',94,1471770,4092.89);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','SEVRAN',61,1279008,3168.26);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','TREMBLAY-EN-FRANCE',84,1353318,3680.02);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','VILLEMOMBLE',320,1566331,4577.65);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','SEINE-SAINT-DENIS','VILLEPINTE',54,1485809,4180.17);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-D''OISE','ARGENTEUIL',295,1623530,6107.62);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-D''OISE','CERGY',156,1278654,2297.5);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-D''OISE','CORMEILLES-EN-PARISIS',235,1397217,3587.22);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-D''OISE','DEUIL-LA-BARRE',215,1390526,3391.9);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-D''OISE','EAUBONNE',281,1337503,3030);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-D''OISE','ERMONT',219,1285463,2767.43);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-D''OISE','FRANCONVILLE',127,1419630,4984.2);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-D''OISE','HERBLAY',183,1451413,4052.26);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-D''OISE','MONTMORENCY',557,1618994,5165.5);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-D''OISE','PONTOISE',199,1513504,4358.39);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-D''OISE','SAINT-GRATIEN',227,1543314,4418.57);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-D''OISE','SANNOIS',144,1461313,3901.9);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-D''OISE','SARCELLES',81,1327890,2604.9);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-D''OISE','TAVERNY',188,1350753,3123.83);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','ALFORTVILLE',121,1424925,3373.76);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','CACHAN',234,1441774,3587.73);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','CHAMPIGNY-SUR-MARNE',335,1459769,4080.78);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','CHARENTON-LE-PONT',658,1543828,4319.96);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','CHOISY-LE-ROI',172,1507976,4871.49);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','CRETEIL',441,1438528,3567.05);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','FONTENAY-SOUS-BOIS',876,1729115,5735.83);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','FRESNES',108,1389167,3494.19);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','IVRY-SUR-SEINE',200,1706949,6586.39);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','L''HAY-LES-ROSES',410,1398490,3507.51);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','LE KREMLIN-BICETRE',125,1352736,3403.33);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','LE PERREUX-SUR-MARNE',727,1518919,4129.81);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','MAISONS-ALFORT',477,1450411,3800.62);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','NOGENT-SUR-MARNE',1156,1713806,5732.68);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','ORLY',67,1312350,2846.51);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','SAINT-MANDE',1163,1837790,6934.66);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','SAINT-MAUR-DES-FOSSES',2570,1687078,5795.6);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','SUCY-EN-BRIE',393,1363227,3123.21);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','THIAIS',246,1497044,4325.84);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','VILLEJUIF',208,1400052,3760.9);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','VILLENEUVE-SAINT-GEORGES',53,1406913,3698.92);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','VILLIERS-SUR-MARNE',157,1428506,4181.05);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','VINCENNES',1468,1549004,4276.65);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','VAL-DE-MARNE','VITRY-SUR-SEINE',260,1343089,2804.37);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','YVELINES','ACHERES',66,1334045,3121.94);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','YVELINES','CHATOU',1077,1708706,5933.12);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','YVELINES','CONFLANS-SAINTE-HONORINE',225,1340353,3375.67);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','YVELINES','ELANCOURT',145,1232432,2309.8);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','YVELINES','GUYANCOURT',129,1260315,2379.71);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','YVELINES','HOUILLES',307,1300247,2523.51);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','YVELINES','LA CELLE-SAINT-CLOUD',872,1767967,6090.73);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','YVELINES','LE CHESNAY',1274,1573981,5166.7);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','YVELINES','LES MUREAUX',53,1292187,2838.13);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','YVELINES','MAISONS-LAFFITTE',1006,1586071,4469.34);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','YVELINES','MANTES-LA-JOLIE',173,1639828,5428.48);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','YVELINES','MONTIGNY-LE-BRETONNEUX',228,1276998,2972.71);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','YVELINES','PLAISIR',250,1366056,2990.77);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','YVELINES','POISSY',296,1383531,3426.81);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','YVELINES','RAMBOUILLET',412,1484499,4200.53);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','YVELINES','SAINT-GERMAIN-EN-LAYE',1830,1763949,5815.91);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','YVELINES','SARTROUVILLE',314,1373956,3308.89);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','YVELINES','VELIZY-VILLACOUBLAY',259,1233481,2436.71);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('ILE-DE-FRANCE','YVELINES','VERSAILLES',4283,1688687,5637.38);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LA REUNION','LA REUNION','LA POSSESSION',104,1581629,3746.03);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LA REUNION','LA REUNION','LE TAMPON',193,1660289,4970.47);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LA REUNION','LA REUNION','SAINT-ANDRE',85,1490443,3469.2);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LA REUNION','LA REUNION','SAINT-BENOIT',53,1626088,5082.17);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LA REUNION','LA REUNION','SAINT-DENIS',785,1596915,4001.79);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LA REUNION','LA REUNION','SAINT-LOUIS',55,1646495,4953.04);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LA REUNION','LA REUNION','SAINT-PAUL',391,1594032,3945.78);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LA REUNION','LA REUNION','SAINT-PIERRE',205,1711242,5494.36);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LA REUNION','LA REUNION','SAINTE-MARIE',107,1569602,4399.47);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LANGUEDOC-ROUSSILLON','AUDE','CARCASSONNE',263,1493724,3985.31);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LANGUEDOC-ROUSSILLON','AUDE','NARBONNE',327,1483530,3693.6);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LANGUEDOC-ROUSSILLON','GARD','ALES',240,1369921,3161.74);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LANGUEDOC-ROUSSILLON','GARD','NIMES',1189,1552429,4382.78);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LANGUEDOC-ROUSSILLON','HERAULT','AGDE',268,1486818,4083.31);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LANGUEDOC-ROUSSILLON','HERAULT','BEZIERS',484,1620184,4896.84);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LANGUEDOC-ROUSSILLON','HERAULT','FRONTIGNAN',91,1343763,3176.21);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LANGUEDOC-ROUSSILLON','HERAULT','LUNEL',97,1380999,2873.96);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LANGUEDOC-ROUSSILLON','HERAULT','MONTPELLIER',1836,1522793,4272.44);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LANGUEDOC-ROUSSILLON','HERAULT','SETE',337,1646821,5078.37);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LANGUEDOC-ROUSSILLON','PYRENEES-ORIENTALES','PERPIGNAN',823,1572552,4616.36);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LIMOUSIN','CORREZE','BRIVE-LA-GAILLARDE',422,1649548,5273.39);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LIMOUSIN','HAUTE-VIENNE','LIMOGES',952,1710809,6221.82);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LORRAINE','MEURTHE-ET-MOSELLE','LUNEVILLE',91,1563416,3847.4);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LORRAINE','MEURTHE-ET-MOSELLE','NANCY',1112,1638505,5439.27);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LORRAINE','MEURTHE-ET-MOSELLE','VANDOEUVRE-LES-NANCY',136,1301880,2628.51);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LORRAINE','MEUSE','VERDUN',73,1618497,4767.93);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LORRAINE','MOSELLE','FORBACH',66,1621513,4921.58);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LORRAINE','MOSELLE','METZ',737,1668985,5592.46);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LORRAINE','MOSELLE','MONTIGNY-LES-METZ',197,1537893,4742.88);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LORRAINE','MOSELLE','SARREGUEMINES',117,1750715,4430.44);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LORRAINE','MOSELLE','THIONVILLE',334,1746409,5491.34);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LORRAINE','VOSGES','EPINAL',228,1750783,6621.77);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('LORRAINE','VOSGES','SAINT-DIE-DES-VOSGES',106,1557139,4037.55);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('MARTINIQUE','MARTINIQUE','FORT-DE-FRANCE',132,2227073,8814.08);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('MARTINIQUE','MARTINIQUE','SCHOELCHER',71,2029619,10343.59);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('MIDI-PYRENEES','AVEYRON','MILLAU',137,1416638,3332.14);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('MIDI-PYRENEES','AVEYRON','RODEZ',238,1554927,4681.34);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('MIDI-PYRENEES','GERS','AUCH',165,1439448,4179.36);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('MIDI-PYRENEES','HAUTE-GARONNE','BLAGNAC',165,1425351,3597.92);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('MIDI-PYRENEES','HAUTE-GARONNE','COLOMIERS',169,1428867,3362.76);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('MIDI-PYRENEES','HAUTE-GARONNE','MURET',174,1365365,3358.88);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('MIDI-PYRENEES','HAUTE-GARONNE','TOULOUSE',4283,1592875,5200.66);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('MIDI-PYRENEES','HAUTE-GARONNE','TOURNEFEUILLE',304,1541737,4368.07);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('MIDI-PYRENEES','HAUTES-PYRENEES','TARBES',210,1398188,3390.59);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('MIDI-PYRENEES','LOT','CAHORS',151,1330521,3594.05);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('MIDI-PYRENEES','TARN','ALBI',312,1504915,4291.95);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('MIDI-PYRENEES','TARN','CASTRES',257,1498200,4376.4);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('MIDI-PYRENEES','TARN-ET-GARONNE','MONTAUBAN',347,1731286,5921.36);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','NORD','ARMENTIERES',94,1670764,6099.63);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','NORD','CAMBRAI',256,1583678,4259.27);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','NORD','CROIX',423,2781074,15018.48);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','NORD','DOUAI',334,1511385,3580.69);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','NORD','DUNKERQUE',461,1404703,3491.73);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','NORD','HALLUIN',91,1503509,3783.25);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','NORD','HAZEBROUCK',155,1521520,4057.55);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','NORD','LA MADELEINE',239,1732564,5127.02);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','NORD','LAMBERSART',412,1728337,5622.81);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','NORD','LILLE',1525,1620315,4860.29);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','NORD','LOOS',59,1438006,2971.49);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','NORD','MARCQ-EN-BAROEUL',1217,2006438,9340.91);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','NORD','MAUBEUGE',97,1356264,3582.44);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','NORD','MONS-EN-BAROEUL',86,1702088,5707.21);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','NORD','ROUBAIX',286,1724840,5507.79);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','NORD','TOURCOING',278,1393321,3309.41);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','NORD','VALENCIENNES',339,1485270,3859.99);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','NORD','VILLENEUVE-D''ASCQ',575,1851093,6044.69);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','NORD','WATTRELOS',54,1233531,2127.63);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','PAS-DE-CALAIS','ARRAS',315,1608794,5054.83);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','PAS-DE-CALAIS','BETHUNE',201,1504948,3906.85);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','PAS-DE-CALAIS','BOULOGNE-SUR-MER',167,1627421,4517.12);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','PAS-DE-CALAIS','CALAIS',223,1516116,4473.89);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','PAS-DE-CALAIS','HENIN-BEAUMONT',71,1513455,4156.89);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('NORD-PAS-DE-CALAIS','PAS-DE-CALAIS','LENS',120,1573661,4662.82);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PAYS DE LA LOIRE','LOIRE-ATLANTIQUE','NANTES',3764,1631933,4909.08);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PAYS DE LA LOIRE','LOIRE-ATLANTIQUE','ORVAULT',367,1496755,4115.22);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PAYS DE LA LOIRE','LOIRE-ATLANTIQUE','REZE',146,1368747,2956.62);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PAYS DE LA LOIRE','LOIRE-ATLANTIQUE','SAINT-HERBLAIN',188,1314938,2750.11);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PAYS DE LA LOIRE','LOIRE-ATLANTIQUE','SAINT-NAZAIRE',340,1405057,3749.79);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PAYS DE LA LOIRE','LOIRE-ATLANTIQUE','SAINT-SEBASTIEN-SUR-LOIRE',214,1490528,4195.62);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PAYS DE LA LOIRE','LOIRE-ATLANTIQUE','VERTOU',269,1630353,4915.48);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PAYS DE LA LOIRE','MAINE-ET-LOIRE','ANGERS',1212,1512104,4280.43);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PAYS DE LA LOIRE','MAINE-ET-LOIRE','CHOLET',411,1468363,3694.5);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PAYS DE LA LOIRE','MAINE-ET-LOIRE','SAUMUR',213,1400257,3451.68);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PAYS DE LA LOIRE','MAYENNE','LAVAL',365,1639645,5556.78);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PAYS DE LA LOIRE','SARTHE','LE MANS',1002,1514851,4313.49);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PAYS DE LA LOIRE','VENDEE','LA ROCHE-SUR-YON',335,1501976,3953.93);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PICARDIE','AISNE','LAON',130,1562554,4166.16);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PICARDIE','AISNE','SAINT-QUENTIN',294,1527742,3886.95);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PICARDIE','AISNE','SOISSONS',265,1594456,4348);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PICARDIE','OISE','BEAUVAIS',319,1740937,6166.33);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PICARDIE','OISE','COMPIEGNE',556,1713549,6454.79);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PICARDIE','SOMME','ABBEVILLE',150,1484334,3878.79);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PICARDIE','SOMME','AMIENS',903,1538827,4592.12);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('POITOU-CHARENTES','CHARENTE','ANGOULEME',298,1541801,4643.08);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('POITOU-CHARENTES','CHARENTE','COGNAC',144,1599549,5020.59);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('POITOU-CHARENTES','CHARENTE-MARITIME','LA ROCHELLE',1037,1553564,4752.19);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('POITOU-CHARENTES','CHARENTE-MARITIME','ROCHEFORT',134,1358671,3217.63);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('POITOU-CHARENTES','CHARENTE-MARITIME','SAINTES',185,1378082,3191.8);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('POITOU-CHARENTES','DEUX-SEVRES','NIORT',443,1613135,5526.9);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('POITOU-CHARENTES','VIENNE','CHATELLERAULT',173,1438562,3697.73);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('POITOU-CHARENTES','VIENNE','POITIERS',556,1678964,7864.29);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','ALPES-DE-HAUTE-PROVENCE','MANOSQUE',251,1412309,4251.31);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','ALPES-MARITIMES','ANTIBES',1692,1589009,4851.69);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','ALPES-MARITIMES','CAGNES-SUR-MER',677,1452266,4046.44);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','ALPES-MARITIMES','CANNES',2339,1894061,7586.32);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','ALPES-MARITIMES','GRASSE',589,1515258,4561.05);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','ALPES-MARITIMES','LE CANNET',665,1748605,6199.92);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','ALPES-MARITIMES','MANDELIEU-LA-NAPOULE',623,1553866,4899.47);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','ALPES-MARITIMES','MENTON',411,1456970,4134.39);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','ALPES-MARITIMES','MONACO',443,2365518,12655.13);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','ALPES-MARITIMES','NICE',5111,1559694,4836.85);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','ALPES-MARITIMES','SAINT-LAURENT-DU-VAR',349,1460354,4032.24);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','ALPES-MARITIMES','VALLAURIS',532,1547022,4283.46);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','BOUCHES-DU-RHONE','AIX-EN-PROVENCE',2935,1639950,5228.25);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','BOUCHES-DU-RHONE','ARLES',324,1530956,4047.79);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','BOUCHES-DU-RHONE','AUBAGNE',378,1560902,4881.75);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','BOUCHES-DU-RHONE','GARDANNE',97,1332167,2987.32);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','BOUCHES-DU-RHONE','ISTRES',129,1392944,2532.02);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','BOUCHES-DU-RHONE','LA CIOTAT',430,1458158,3812.1);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','BOUCHES-DU-RHONE','LES PENNES-MIRABEAU',123,1371356,3110.48);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','BOUCHES-DU-RHONE','MARIGNANE',130,1434660,3136.45);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','BOUCHES-DU-RHONE','MARSEILLE',6247,1673436,5584.62);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','BOUCHES-DU-RHONE','MARTIGUES',209,1327865,3265.66);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','BOUCHES-DU-RHONE','SALON-DE-PROVENCE',292,1440483,3370.43);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','BOUCHES-DU-RHONE','VITROLLES',71,1383542,4521.76);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','HAUTES-ALPES','GAP',370,1483097,3542.24);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','VAR','DRAGUIGNAN',429,1409810,3538.74);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','VAR','FREJUS',712,1454753,3779.51);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','VAR','HYERES',1072,1412454,3586.06);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','VAR','LA GARDE',197,1535958,3660.75);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','VAR','LA SEYNE-SUR-MER',302,1316152,2955.61);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','VAR','LA VALETTE-DU-VAR',173,1385038,3418.17);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','VAR','SAINT-RAPHAEL',1344,1515535,4243.62);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','VAR','SIX-FOURS-LES-PLAGES',522,1380090,3139.98);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','VAR','TOULON',1339,1425245,4086.43);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','VAUCLUSE','AVIGNON',577,1618573,4929.09);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','VAUCLUSE','CARPENTRAS',224,1569304,4570.45);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','VAUCLUSE','CAVAILLON',189,1420799,3477.96);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('PROVENCE-ALPES-COTE D''AZUR','VAUCLUSE','ORANGE',182,1395366,2991.24);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','AIN','BOURG-EN-BRESSE',305,1463866,4037.33);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','AIN','OYONNAX',166,1965518,8644.07);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','DROME','MONTELIMAR',268,1520840,3715.5);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','DROME','ROMANS-SUR-ISERE',193,1455326,3244.3);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','DROME','VALENCE',493,1631920,5552.83);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','HAUTE-SAVOIE','ANNECY',898,1499041,4759.88);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','HAUTE-SAVOIE','ANNECY-LE-VIEUX',660,1493505,3819.61);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','HAUTE-SAVOIE','ANNEMASSE',223,1324337,2781.33);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','HAUTE-SAVOIE','THONON-LES-BAINS',404,1787068,7280.99);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','ISERE','BOURGOIN-JALLIEU',152,1569239,4757.06);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','ISERE','ECHIROLLES',113,1215636,2306.78);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','ISERE','GRENOBLE',1425,1541696,4690.46);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','ISERE','SAINT-MARTIN-D''HERES',87,1425506,3610.45);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','ISERE','VIENNE',240,1453635,3606.13);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','ISERE','VOIRON',198,1533862,4188.55);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','LOIRE','ROANNE',178,1526408,3957.96);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','LOIRE','SAINT-CHAMOND',151,1570336,5969.09);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','LOIRE','SAINT-ETIENNE',964,1615587,5013.67);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','RHONE','BRON',329,1434552,3179.2);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','RHONE','CALUIRE-ET-CUIRE',920,1656393,4928.08);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','RHONE','DECINES-CHARPIEU',97,1336988,3316.82);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','RHONE','LYON',6936,1685208,5377.18);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','RHONE','MEYZIEU',159,1652906,5280.24);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','RHONE','OULLINS',129,1404637,3490.46);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','RHONE','RILLIEUX-LA-PAPE',168,1584882,3896.04);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','RHONE','SAINT-GENIS-LAVAL',296,1480885,3891.29);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','RHONE','SAINT-PRIEST',142,1582238,5362.82);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','RHONE','SAINTE-FOY-LES-LYON',627,1704375,6419.94);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','RHONE','VENISSIEUX',67,1545584,4413.04);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','RHONE','VILLEFRANCHE-SUR-SAONE',196,1563965,4569.91);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','RHONE','VILLEURBANNE',519,1398366,3307.57);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','SAVOIE','AIX-LES-BAINS',395,1340078,3078.37);
INSERT INTO isf_france(region,departement,commune,nb_redevables,patrimoine_moyen,impot_moyen) VALUES ('RHONE-ALPES','SAVOIE','CHAMBERY',691,1508811,4409.66);
